### ISSUE TITLE
 Tables in H2 have not been created

### ISSUE THREAD

**Issue by vitaliiHHU** [vitaliiHHU/JPATutorial#5]

**Comment by Spring3** [comment]
@vitaliiHHU You need not use ``in-memory`` type of a database. Try selecting the ``Embedded`` and change the url in ``persistence.xml`` accordingly.
<img width="514" alt="screen shot 2017-01-20 at 21 08 42" src="https://cloud.githubusercontent.com/assets/4171202/22161832/a9a386ce-df54-11e6-8d55-032d410b718b.png">
